# Домашнее задание 2

In [ ]:
import pandas as pd

#### Описание данных

В папке Dat (https://github.com/hse-ds/iad-intro-ds/blob/master/2023/homeworks/Data.zip) находится информация о студентах. Всего 10 групп студентов. Файлы делятся на две категории:
    * Students_info_i - информация о студентах из группы i
    * Students_marks_i - оценки студентов из группы i за экзамены

### Одно из важных достоинств pandas $-$ это удобные методы реляционного взаимодействия с данными, аналогичные, например, возможностям SQL для слияния и конкатенации таблиц: merge, join, concat. Наличие готовых методов позволяет не реализовывать самостоятельно поэлементную обработку данных и оперировать сразу целыми таблицами данных.

Подробно об этих методах посмотрите тут: https://www.kaggle.com/residentmario/renaming-and-combining#Combining

#### Задание 1. Соберите всю информацию о студентах в одну таблицу df. В получившейся таблице должна быть информация и оценки всех студентов из всех групп. Напечатайте несколько строк таблицы для демонстрации результата.¶

In [ ]:
!wget https://github.com/hse-ds/iad-intro-ds/raw/master/2023/homeworks/Data.zip
!unzip /content/Data.zip

--2024-02-09 09:07:27--  https://github.com/hse-ds/iad-intro-ds/raw/master/2023/homeworks/Data.zip
Resolving github.com (github.com)... 140.82.113.4
Connecting to github.com (github.com)|140.82.113.4|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/hse-ds/iad-intro-ds/master/2023/homeworks/Data.zip [following]
--2024-02-09 09:07:27--  https://raw.githubusercontent.com/hse-ds/iad-intro-ds/master/2023/homeworks/Data.zip
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.110.133, 185.199.111.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 16727 (16K) [application/zip]
Saving to: ‘Data.zip’

Data.zip            100%[===================>]  16.33K  --.-KB/s    in 0s

2024-02-09 09:07:27 (46.2 MB/s) - ‘Data.zip’ saved [16727/16727]

Archive:  /content/Data.zip
   creating: Data/
  inflating: Data/Students_info_0.csv
  inflating: Data/Students_info_1.csv
  inflating: Data/Students_info_2.csv
  inflating: Data/Students_info_3.csv
  inflating: Data/Students_info_4.csv
  inflating: Data/Students_info_5.csv
  inflating: Data/Students_info_6.csv
  inflating: Data/Students_info_7.csv
  inflating: Data/Students_info_8.csv
  inflating: Data/Students_info_9.csv
  inflating: Data/Students_marks_0.csv
  inflating: Data/Students_marks_1.csv
  inflating: Data/Students_marks_2.csv
  inflating: Data/Students_marks_3.csv
  inflating: Data/Students_marks_4.csv
  inflating: Data/Students_marks_5.csv
  inflating: Data/Students_marks_6.csv
  inflating: Data/Students_marks_7.csv
  inflating: Data/Students_marks_8.csv
  inflating: Data/Students_marks_9.csv

In [ ]:
info_files = [f"/content/Data/Students_info_{i}.csv" for i in range(10)]
marks_files = [f"/content/Data/Students_marks_{i}.csv" for i in range(10)]


info_dfs = [pd.read_csv(file) for file in info_files]
students_info_df = pd.concat(info_dfs)


marks_dfs = [pd.read_csv(file) for file in marks_files]
students_marks_df = pd.concat(marks_dfs)


df = pd.merge(students_info_df, students_marks_df, on='index')

print(df.head())

   index  gender race/ethnicity parental level of education         lunch  \
0      0  female        group B           bachelor's degree      standard
1      1  female        group C                some college      standard
2      2  female        group B             master's degree      standard
3      3    male        group A          associate's degree  free/reduced
4      4    male        group C                some college      standard

  test preparation course   group  math score  reading score  writing score
0                    none  group1          72             72             74
1               completed  group1          69             90             88
2                    none  group1          90             95             93
3                    none  group1          47             57             44
4                    none  group1          76             78             75

#### Задание 2. Удалите столбец index у полученной таблицы. Напечатайте первые 10 строк таблицы.

In [ ]:
df = df.drop(columns=['index'])

df.head(10)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,group,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,group1,72,72,74
1,female,group C,some college,standard,completed,group1,69,90,88
2,female,group B,master's degree,standard,none,group1,90,95,93
3,male,group A,associate's degree,free/reduced,none,group1,47,57,44
4,male,group C,some college,standard,none,group1,76,78,75
5,female,group B,associate's degree,standard,none,group1,71,83,78
6,female,group B,some college,standard,completed,group1,88,95,92
7,male,group B,some college,free/reduced,none,group1,40,43,39
8,male,group D,high school,free/reduced,completed,group1,64,64,67
9,female,group B,high school,free/reduced,none,group1,38,60,50

#### Задание 3. Выведите на экран размеры полученной таблицы

In [ ]:
df.shape

(2000, 9)

#### Задание 4. Выведите на экран статистические характеристики числовых столбцов таблицы (минимум, максимум, среднее значение, стандартное отклонение)

In [ ]:
df.describe()

        math score  reading score  writing score
count  2000.000000     2000.00000    2000.000000
mean     66.089000       69.16900      68.054000
std      15.159287       14.59654      15.191856
min       0.000000       17.00000      10.000000
25%      57.000000       59.00000      57.750000
50%      66.000000       70.00000      69.000000
75%      77.000000       79.00000      79.000000
max     100.000000      100.00000     100.000000

#### Задание 5. Проверьте, есть ли в таблице пропущенные значения

In [ ]:
missing = df.isna().any()

print(missing.any())
print(missing[missing].index.tolist())

False
[]

#### Задание 6. Выведите на экран средние баллы студентов по каждому предмету (math, reading, writing)

In [ ]:
print(df['math score'].mean())
print(df['reading score'].mean())
print(df['writing score'].mean())

66.089
69.169
68.054

**Задание 7. Как зависят оценки от того, проходил ли студент курс для подготовки к сдаче экзамена (test preparation course)? Выведите на экран для каждого предмета в отдельности средний балл студентов, проходивших курс для подготовки к экзамену и не проходивших курс.**

In [ ]:
average_score = df.groupby('test preparation course').mean()

average_score[['math score', 'reading score', 'writing score']]

<ipython-input-7-96fc35bfe33f>:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  average_score = df.groupby('test preparation course').mean()

                         math score  reading score  writing score
test preparation course
completed                 69.695531      73.893855      74.418994
none                      64.077882      66.534268      64.504673

**Задание 8. Выведите на экран все различные значения из столбца lunch.**

In [ ]:
df['lunch'].unique()

array(['standard', 'free/reduced'], dtype=object)

**Задание 9. Переименуйте колонку "parental level of education" в "education", а "test preparation course" в "test preparation" с помощью метода pandas rename**
https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.rename.html

In [ ]:
df = df.rename(columns={"parental level of education": "education", "test preparation course": "test preparation"})

df

,gender,race/ethnicity,education,lunch,test preparation,group,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,group1,72,72,74
1,female,group C,some college,standard,completed,group1,69,90,88
2,female,group B,master's degree,standard,none,group1,90,95,93
3,male,group A,associate's degree,free/reduced,none,group1,47,57,44
4,male,group C,some college,standard,none,group1,76,78,75
...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,group10,88,99,95
996,male,group C,high school,free/reduced,none,group10,62,55,55
997,female,group C,high school,free/reduced,completed,group10,59,71,65
998,female,group D,some college,standard,completed,group10,68,78,77
999,female,group D,some college,free/reduced,none,group10,77,86,86

**Зафиксируем минимальный балл для сдачи экзамена**

In [ ]:
passmark = 50

**Задание 10. Ответьте на вопросы:**
    * Какая доля студентов сдала экзамен по математике (passmark >= 50)?
    * Какая доля студентов, проходивших курс подготовки к экзамену, сдала экзамен по математике?
    * Какая доля женщин, не проходивших курс подготовки к экзамену, не сдала экзамен по математике?

In [ ]:
passing_course = df[(df['test preparation'] == 'completed') & (df['math score'] >= passmark)]
without_course = df[(df['gender'] == 'female') & (df['test preparation'] == 'none')]
without_course_failure = df[(df['gender'] == 'female') & (df['test preparation'] == 'none') & (df['math score'] < passmark)]

print((len(df[df['math score'] >= passmark])) / len(df))

print(len(passing_course) / len(df[df['test preparation'] == 'completed']))

print(len(without_course_failure) / len(without_course))

0.865
0.9217877094972067
0.20958083832335328

**Задание 11. С помощью groupby выполните задания ниже. Также выведите время выполнения каждого из заданий.**
    * Для каждой этнической группы выведите средний балл за экзамен по чтению
    * Для каждого уровня образования выведите минимальный балл за экзамен по письму

In [ ]:
import time

In [ ]:
start_time = time.time()
averege_score = df.groupby('race/ethnicity')['reading score'].mean()

print(averege_score)
print((time.time() - start_time))

race/ethnicity
group A    64.674157
group B    67.352632
group C    69.103448
group D    70.030534
group E    73.028571
Name: reading score, dtype: float64
0.004086732864379883

In [ ]:
start_time = time.time()
min_score = df.groupby('education')['writing score'].min()

print(min_score)
print((time.time() - start_time))

education
associate's degree    35
bachelor's degree     38
high school           15
master's degree       46
some college          19
some high school      10
Name: writing score, dtype: int64
0.006297111511230469

**Задание 12. Выполните задание 11 с помощью циклов. Сравните время выполнения.**

In [ ]:
start_time = time.time()
ethnicities = df['race/ethnicity'].unique()

for ethnicity in ethnicities:
    average_score = df[df['race/ethnicity'] == ethnicity]['reading score'].mean()
    print(ethnicity, average_score)

print((time.time() - start_time))

group B 67.35263157894737
group C 69.10344827586206
group A 64.67415730337079
group D 70.03053435114504
group E 73.02857142857142
0.013004779815673828

In [ ]:
start_time = time.time()
ed_lvls = df['education'].unique()

for ed_lvl in ed_lvls:
    min_score = df[df['education'] == ed_lvl]['writing score'].min()
    print(ed_lvl, min_score)

print((time.time() - start_time))

bachelor's degree 38
some college 19
master's degree 46
associate's degree 35
high school 15
some high school 10
0.01445460319519043

**Задание 13. Выведите на экран средние баллы студентов по каждому предмету в зависимости от пола и уровня образования. То есть должно получиться количество групп, равных 2 * (число уровней образования), и для каждой такой группы выыведите средний балл по каждому из предметов.**

Это можно сделать с помощью сводных таблиц (pivot_table):

https://www.kaggle.com/kamilpolak/tutorial-how-to-use-pivot-table-in-pandas

In [ ]:
grouped= pd.pivot_table(df, index=['gender', 'education'], values=['math score', 'reading score', 'writing score'], aggfunc='mean')

grouped

                           math score  reading score  writing score
gender education
female associate's degree   65.250000      74.120690      74.000000
       bachelor's degree    68.349206      77.285714      78.380952
       high school          59.351064      68.202128      66.691489
       master's degree      66.500000      76.805556      77.638889
       some college         65.406780      73.550847      74.050847
       some high school     59.296703      69.109890      68.285714
male   associate's degree   70.764151      67.433962      65.405660
       bachelor's degree    70.581818      68.090909      67.654545
       high school          64.705882      61.480392      58.539216
       master's degree      74.826087      73.130435      72.608696
       some college         69.009259      64.990741      63.148148
       some high school     67.840909      64.693182      61.375000

#### Задание 14. Сколько студентов успешно сдали экзамен по математике?

Создайте новый столбец в таблице df под названием Math_PassStatus и запишите в него F, если студент не сдал экзамен по математике (балл за экзамен < passmark), и P иначе.

Посчитайте количество студентов, сдавших и не сдавших экзамен по математике.

Сделайте аналогичные шаги для экзаменов по чтению и письму.

In [ ]:
df['Math_PassStatus'] = df['math score'].apply(lambda x: 'P' if x >= passmark else 'F')
df['Reading_PassStatus'] = df['reading score'].apply(lambda x: 'P' if x >= passmark else 'F')
df['Writing_PassStatus'] = df['writing score'].apply(lambda x: 'P' if x >= passmark else 'F')

math_passed = df['Math_PassStatus'].value_counts()
reading_passed = df['Reading_PassStatus'].value_counts()
writing_passed = df['Writing_PassStatus'].value_counts()

print(math_passed)
print(reading_passed)
print(writing_passed)

P    865
F    135
Name: Math_PassStatus, dtype: int64
P    910
F     90
Name: Reading_PassStatus, dtype: int64
P    886
F    114
Name: Writing_PassStatus, dtype: int64

#### Задание 15. Сколько студентов успешно сдали все экзамены?

Создайте столбец OverAll_PassStatus и запишите в него для каждого студента 'F', если студент не сдал хотя бы один из трех экзаменов, а иначе 'P'.

Посчитайте количество студентов, которые сдали все экзамены.

In [ ]:
df['OverAll_PassStatus'] = df.apply(lambda x : 'F' if x['Math_PassStatus'] == 'F' or x['Reading_PassStatus'] == 'F' or x['Writing_PassStatus'] == 'F' else 'P', axis =1)

df.OverAll_PassStatus.value_counts()

P    812
F    188
Name: OverAll_PassStatus, dtype: int64

#### Задание 16. Переведем баллы в оценки

### Система перевода баллов в оценки
####    больше 90 = A
####      80-90 = B
####      70-80 = C
####      60-70 = D
####      50-60 = E
####    меньше 50 = F (Fail)

Создайте вспомогательную функцию, которая будет по среднему баллу за три экзамена выставлять оценку студенту по данным выше критериям.

Создайте столбец Grade и запишите в него оценку каждого студента.

Выведите количество студентов, получивших каждую из оценок.

**В случае, если средний балл попадает на границу между оценками (т.е. равен ровно 60, 70 или 80 баллов), вы можете интерпретировать условие на своё усмотрение (т.е. можете поставить за 60 баллов оценку D, а можете - E).**

In [ ]:
def GetGrade(average_mark):
    if average_mark > 90:
        return 'A'
    elif 80 <= average_mark <= 90:
        return 'B'
    elif 70 <= average_mark < 80:
        return 'C'
    elif 60 <= average_mark < 70:
        return 'D'
    elif 50 <= average_mark < 60:
        return 'E'
    else:
        return 'F'

df['Average'] = df[['math score', 'reading score', 'writing score']].mean(axis=1)

df['Grade'] = df['Average'].apply(GetGrade)

grade_counts = df['Grade'].value_counts()

print(grade_counts)

C    261
D    256
E    182
B    148
F    103
A     50
Name: Grade, dtype: int64